# Generated by Django 3.2 on 2021-05-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
