# Generated by Django 3.2 on 2021-05-27 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210527_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
