# Generated by Django 3.2 on 2021-05-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='delete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
