# Generated by Django 3.2 on 2021-05-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210527_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='delete',
        ),
    ]
