# Generated by Django 3.2 on 2021-05-27 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
