# Generated by Django 3.2 on 2021-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
