# Generated by Django 3.2 on 2021-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210527_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
