# Generated by Django 3.2 on 2021-06-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210602_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='current_price',
            new_name='starting_price',
        ),
    ]
