# Generated by Django 3.2 on 2021-07-04 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_current_price_auctionlisting_starting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bidder',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ManyToManyField(default=None, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='highest_bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
