# Generated by Django 3.2 on 2021-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210704_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
