# Generated by Django 3.2 on 2021-07-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210709_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='auctions.auctionlisting'),
        ),
    ]
